import {
  Accordion,
  AccordionBody,
  AccordionHeader,
  Avatar,
  Badge,
  Breadcrumbs,
  Button,
  Box,
  Calendar,
  Card,
  CardBody,
  CardFooter,
  CardHeader,
  Checkbox,
  Chip,
  ColumnContainer,
  ContextMenu,
  ContextMenuRoot,
  ContextMenuTarget,
  CustomOption,
  CustomSelect,
  DataGrid,
  Divider,
  Drawer,
  DrawerTarget,
  DrawerWrapper,
  Dropdown,
  DropdownHeader,
  DropdownMenu,
  FloatingActionButton,
  Footer,
  Form,
  Grid,
  GridCol,
  GridItem,
  Header,
  Icon,
  Image,
  Input,
  Label,
  Link,
  List,
  ListItem,
  CollapsibleListItem,
  Loader,
  Menu,
  MenuTarget,
  MenuItem,
  Option,
  Pagination,
  Progress,
  Radio,
  RangeSlider,
  Rating,
  RowContainer,
  ScrollArea,
  Select,
  Sidebar,
  Slider,
  // Stack,
  Stepper,
  Step,
  StepContent,
  StepLabel,
  Switch,
  Table,
  TableBody,
  TableCell,
  TableCaption,
  TableFoot,
  TableHeader,
  TableHeaderCell,
  TableRow,
  TabsProvider,
  Tabs,
  TextArea,
  Tooltip,
  Typography,
  // new components added on 29-01-2024
  Carousel,
  CarouselItem,
  ComboBox,
  DateRangePicker,
  Kanban,
  ModalContainer,
  ModalProvider,
  ModalTarget,
  MultiSelect,
  PopoverRoot,
  PopoverTarget,
  PopoverPopup,
  TodoCalendar,
  Video,
  VerticalCarouselAnimationWrapper,
  VerticalCarouselAnimationItem,
  Tab,
  Panel,
} from "@purecodeai/pcui";

export const ComponentMapping = {
  Accordion: Accordion,
  AccordionBody: AccordionBody,
  AccordionHeader: AccordionHeader,
  Avatar: Avatar,
  Badge: Badge,
  Breadcrumbs: Breadcrumbs,
  Button: Button,
  Box: Box,
  Calendar: Calendar,
  Card: Card,
  CardBody: CardBody,
  CardFooter: CardFooter,
  CardHeader: CardHeader,
  Checkbox: Checkbox,
  Chip: Chip,
  Dropdown: Dropdown,
  DropdownHeader: DropdownHeader,
  DropdownMenu: DropdownMenu,
  Footer: Footer,
  Form: Form,
  Header: Header,
  Icon: Icon,
  Image: Image,
  Input: Input,
  Label: Label,
  Link: Link,
  List: List,
  ListItem: ListItem,
  CollapsibleListItem: CollapsibleListItem,
  Loader: Loader,
  Option: Option,
  Pagination: Pagination,
  Progress: Progress,
  Radio: Radio,
  Rating: Rating,
  Select: Select,
  Sidebar: Sidebar,
  Slider: Slider,
  Stepper: Stepper,
  Step: Step,
  StepContent: StepContent,
  StepHeader: StepLabel,
  Switch: Switch,
  Table: Table,
  TableBody: TableBody,
  TableCell: TableCell,
  TableHeader: TableHeader,
  TableRow: TableRow,
  TabsProvider: TabsProvider,
  Tabs: Tabs,
  Tab: Tab,
  Panel: Panel,
  Textarea: TextArea,
  Tooltip: Tooltip,
  Typography: Typography,
  // newly added components
  // Col: Col,
  // Colgroup: Colgroup,
  ColumnContainer: ColumnContainer,
  ContextMenu: ContextMenu,
  ContextMenuRoot: ContextMenuRoot,
  ContextMenuTarget: ContextMenuTarget,
  CustomOption: CustomOption,
  CustomSelect: CustomSelect,
  DataGrid: DataGrid,
  Divider: Divider,
  Drawer: Drawer,
  DrawerTarget: DrawerTarget,
  DrawerWrapper: DrawerWrapper,
  FloatingActionButton: FloatingActionButton,
  Grid: Grid,
  GridCol: GridCol,
  GridItem: GridItem,
  Menu: Menu,
  MenuTarget: MenuTarget,
  MenuItem: MenuItem,
  RangeSlider: RangeSlider,
  RowContainer: RowContainer,
  ScrollArea: ScrollArea,
  Stack: Box,
  TableCaption: TableCaption,
  TableFoot: TableFoot,
  TableHeaderCell: TableHeaderCell,
  // new pro component
  Carousel: Carousel,
  CarouselItem: CarouselItem,
  ComboBox: ComboBox,
  DateRangePicker: DateRangePicker,
  Kanban: Kanban,
  ModalContainer: ModalContainer,
  ModalProvider: ModalProvider,
  ModalTarget: ModalTarget,
  MultiSelect: MultiSelect,
  PopoverRoot: PopoverRoot,
  PopoverTarget: PopoverTarget,
  PopoverPopup: PopoverPopup,
  TodoCalendar: TodoCalendar,
  Video: Video,
  VerticalCarouselAnimationWrapper: VerticalCarouselAnimationWrapper,
  VerticalCarouselAnimationItem: VerticalCarouselAnimationItem,
};
