export const dataVideo = {
  accordion:
    "https://purecodestorageprod.blob.core.windows.net/homepage-videos/component/Tailwind/Accordion",
  accountsetting:
    "https://purecodestorageprod.blob.core.windows.net/homepage-videos/component/Tailwind/Account-Setting",
  actionpanel:
    "https://purecodestorageprod.blob.core.windows.net/homepage-videos/component/Tailwind/Action-Panel",
  checkboxlist:
    "https://purecodestorageprod.blob.core.windows.net/homepage-videos/component/Tailwind/Checkbox-List",
  contactus:
    "https://purecodestorageprod.blob.core.windows.net/homepage-videos/component/Tailwind/Contact-Us",
  descriptionlist:
    "https://purecodestorageprod.blob.core.windows.net/homepage-videos/component/Tailwind/Description-List",
  emptystate:
    "https://purecodestorageprod.blob.core.windows.net/homepage-videos/component/Tailwind/Empty-State",
  faqs: "https://purecodestorageprod.blob.core.windows.net/homepage-videos/component/Tailwind/FAQs",
  feedbackform:
    "https://purecodestorageprod.blob.core.windows.net/homepage-videos/component/Tailwind/Feedback-form",
  header:
    "https://purecodestorageprod.blob.core.windows.net/homepage-videos/component/Tailwind/Header",
  herosection:
    "https://purecodestorageprod.blob.core.windows.net/homepage-videos/component/Tailwind/Hero-Section",
  invoice:
    "https://purecodestorageprod.blob.core.windows.net/homepage-videos/component/Tailwind/Invoice",
  notification:
    "https://purecodestorageprod.blob.core.windows.net/homepage-videos/component/Tailwind/Notification",
  quickstart:
    "https://purecodestorageprod.blob.core.windows.net/homepage-videos/component/Tailwind/Quick-Start",
  radiogroup:
    "https://purecodestorageprod.blob.core.windows.net/homepage-videos/component/Tailwind/Radio-Group",
  recoverpassword:
    "https://purecodestorageprod.blob.core.windows.net/homepage-videos/component/Tailwind/Recover-Password",
  referral:
    "https://purecodestorageprod.blob.core.windows.net/homepage-videos/component/Tailwind/Referral",
  searchpalette:
    "https://purecodestorageprod.blob.core.windows.net/homepage-videos/component/Tailwind/Search-Palette",
  security:
    "https://purecodestorageprod.blob.core.windows.net/homepage-videos/component/Tailwind/Security",
  sidebar:
    "https://purecodestorageprod.blob.core.windows.net/homepage-videos/component/Tailwind/Sidebar",
  signin:
    "https://purecodestorageprod.blob.core.windows.net/homepage-videos/component/Tailwind/Signin",
  stackedlist:
    "https://purecodestorageprod.blob.core.windows.net/homepage-videos/component/Tailwind/Stacked-List",
  table:
    "https://purecodestorageprod.blob.core.windows.net/homepage-videos/component/Tailwind/Table",
  testimonial:
    "https://purecodestorageprod.blob.core.windows.net/homepage-videos/component/Tailwind/Testimonial",
  signup: "https://purecodestorageprod.blob.core.windows.net/homepage-videos/component/mui/Signup",
};
